project_name: goreleaser-demo
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  binary: hello
  goos:
  - darwin
  - linux
  - windows
  - openbsd
  - freebsd
  goarch:
  - amd64
  - 386
  - arm64
  - arm
dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - "martinhelmich/hello:latest"
  - "martinhelmich/hello:{{ .Tag }}"
  skip_push: true
archive:
  replacements:
    darwin: macos
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
