project_name: helloworld
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  binary: hello
  goos:
  - darwin
  - linux
  - windows
  - openbsd
  - freebsd
  goarch:
  - amd64
  - 386
  - arm64
  - arm
archive:
  replacements:
    darwin: macos
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
