version: "3"
services: 
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "80:80"
      - "22:22"
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
  
  runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  config: {}
  data: {}
  logs: {}
